// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz0amcJ7XyY0m_LhuUYojwMMEehjEo4kM',
    appId: '1:253112985837:web:cdce8902b50752dcaac4e4',
    messagingSenderId: '253112985837',
    projectId: 'tktt-6454a',
    authDomain: 'tktt-6454a.firebaseapp.com',
    storageBucket: 'tktt-6454a.firebasestorage.app',
    measurementId: 'G-DWER831SRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeETh-hri8bpuBvAQTJZq1KcWsM5OTnJo',
    appId: '1:253112985837:android:bf21e29287e3ac28aac4e4',
    messagingSenderId: '253112985837',
    projectId: 'tktt-6454a',
    storageBucket: 'tktt-6454a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx4cF7Sb4U_JlwOWD_tuwuTJ4hF7pjS20',
    appId: '1:253112985837:ios:f2fc6963b02e3fe6aac4e4',
    messagingSenderId: '253112985837',
    projectId: 'tktt-6454a',
    storageBucket: 'tktt-6454a.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
